"""
ws_pipe
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

from airflow.models import Variable
import requests

@aql.dataframe(task_id="fetch_activity")
def fetch_activity_func():
    r = requests.get(Variable.get(API))
    return r.json()

@aql.dataframe(task_id="print_activity")
def print_activity_func(fetch_activity: pd.DataFrame):
    print(fetch_activity)

default_args={
    "owner": "Hugo Herlanin,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-12-15", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Hugo Herlanin": "mailto:hherlanin@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clq6q2x6603jp01puoblcnn9v/cloud-ide/clq6x471s03l501omy1eukc0r/clq6ygdml03rh01pufpy0xugu",
    },
)
def ws_pipe():
    fetch_activity = fetch_activity_func()

    print_activity = print_activity_func(
        fetch_activity,
    )

dag_obj = ws_pipe()
